destroy table inet filter

table inet filter {
	chain input {
		type filter hook input priority filter
		policy drop
		
		iif lo counter accept comment "incoming interface loopback accept"
		ct state invalid counter drop
		ct state {established, related} counter accept comment "connection track if packet related to established connection accept"

		ct state new tcp dport 22 counter accept
		ct state new tcp dport 8080 counter accept
	}
}
