# yaml files don't support tabs, if you accidentally made one using tabs, just run:
# expand -t 2 compose.yaml > fixedcompose.yaml && mv fixedcompose.yaml compose.yaml
# "-t" meaning tab "2" replacing each tab with 2 spaces

services: # services are a list of containers
  nginx: # each container can have its own name being whatever I want
    image: nginx:alpine # nginx is an image and "latest" following the colon is the version, versions aren't always from specific releases and can just be particular editions of an image
    ports: # ports is a list without a key value pair so the syntax is just dashes for each element
      - "8080:80" # forward packets coming through port 8080 on this machine to the container on port 80.
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # ro means read only
  backend:
    image: python:3.13-alpine
    command: python -m http.server 8000
    volumes:
      - ../notes:/Documents
